# Site settings
title: Andrew Prowse  
name: Andrew Prowse

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/andrewprowse
 - title: LinkedIn
   url: https://www.linkedin.com/in/andy-prowse-bb4265b9/

#Any buzzword skills you want to include
skills:
 - Containers
 - Docker
 - Kubernetes
 - Swarm
 - Ansible
 - Bash
 - KVM
 - O-virt
 - Solaris
 - ZFS
 - Certified Instructor
 - Technical Architecture
 - Technical Documentation
 - Scrum

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
# blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Manager - Platform & DevOps
   start: 2013
   end: Ongoing
   employer: HighVail Systems Inc.
   description: Technical lead, solution and delivery expert in Containers, Automation and DevOps, as well as a domain expert in virtualisation, Linux, Unix and cloud technology. I hold technical certifications from Oracle, RedHat, Fujitsu, and Docker. I am an accredited Docker Trainer and member of HighVail’s training team. 
 - title: Senior Open Systems Engineer
   start: 1991
   end: 2012
   employer: Amdahl Canada/Fujitsu Canada
   description: Working both onsite and remotely with Enterprise customers to provide Open Systems support for both Solaris SPARC operating system and hardware, as well as Linux on X86.

#Education is required
education:
 - level: Dipl. T
   date: 1990
   subject: Computer Electronics Engineering Technology
   school: Mohake College of Applied Arts and Sciences

#This section is optional (as is the image link below)
# coursera:
#    profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#    courses:
#     - title: Functional Programming Principles in Scala
#       link: https://www.coursera.org/course/progfun
#       optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#       date: September 16, 2013
#     - title: Algorithms Design and Analysis, Part 1
#       link: https://www.coursera.org/specializations/algorithms
#       optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#       date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
# speakerdeck:
#    profileurl: https://speakerdeck.com/robhinds
#    talks:
#     - title: Product Management for Engineers
#       speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#       conference: API Conference, Berlin 2018
#     - title: Agile Machine Learning - from Theory to Production
#       speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#       conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
# github:
#  - robhinds/robhinds.github.io
#  - robhinds/ScaLambda
#  - robhinds/opinionated-akka-http
#  - robhinds/food2vec
#  - robhinds/microservices
#  - robhinds/spring-social-geeklist
#  - robhinds/spring-social-stackoverflow
#  - robhinds/genotype
#  - robhinds/footweets
#  - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
# stackoverflow:
#    profileurl: http://stackoverflow.com/users/258813/rhinds
#    flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: |
  I am an open systems specialist with 30 years experience working in technology. I have primarily worked with Linux, but have worked across a broad range of technologies thereon: Docker, Kubernetes, Swarm, Ansible, Puppet and currently with Rancher. My experience with enterprise infrastructure has provided a tremendous base for bringing the robustness of HA servers into the world of DevOps through automation and orchestration.  <br/><br/>
  I enjoy system building, and integrating these into the current CI/CD workflows. With a good Product Management focus and an adherence to Agile practices, we can come up with solid solutions to intriguing problems.  <br/><br/>
  I have worked in large scale consultancy roles across North America as well as a mix of support experience (including Enginnering support roles) that has provided me with a deep understanding of the technology landscape.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
# additionalinfo: |
